source 'https://github.com/CocoaPods/Specs.git'

target 'hotUpdate' do
  pod 'AFNetworking',             '~> 3.1.0'
  pod 'ZipArchive',               '~> 1.4.0'
  pod 'React’, :path => ‘../node_modules/react-native’, :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTLinkingIOS',
    'ART',
    'jschelpers_legacy',
    'cxxreact_legacy',
    ]
  pod "Yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'FegoRnUpdate', :path => ‘../../‘
end
